version: '3.6'
services:
  fulafunge:
    image: 'proof-engine:dev'
    restart: always
    network_mode: "host"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      DISPLAY: $DISPLAY
      RUST_LOG: 'warn,fula_funge=info'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '$SSH_AUTH_SOCK:/ssh-agent'
